### ISSUE TITLE
DK_UI_IMPLEMENTATION compiled multiple time.

### ISSUE THREAD

**Issue by harrisyu** [dkvilo/dk_console#1]
When include dk_console.h in multiple files, dk_ui.h will implementation multiple time.

**Comment by dkvilo** [comment]
Hey, could you try these changes, should help with your problem.

https://github.com/dkvilo/dk_console/pull/2/commits/5fd01d514dd367b9fbc54b8b77953a90c6a75a8f

please let me know and I'll merge the changes.

**Comment by harrisyu** [comment]
> Hey, could you try these changes, should help with your problem.
> 
> [5fd01d5](https://github.com/dkvilo/dk_console/commit/5fd01d514dd367b9fbc54b8b77953a90c6a75a8f)
> 
> please let me know and I'll merge the changes.

Yes, it solved my problem, thank you.
